### ISSUE TITLE
Consider always having the function in the last position

### ISSUE THREAD

**Issue by lpil** [MystPi/glen#1]
Hello!

Currently the serve function and other have the function first rather than last, which is the Gleam convention.

Having the function last would mean that they are suitable for `use` expressions, and the formatter will format them nicely.
```gleam
pub fn main() {
  glen.serve(
    fn(request) {
      ...
    }
    8000,
  )
}
```
vs
```gleam
pub fn main() {
  glen.serve(8000, fn(request) {
    ...
  })
}
```

Thanks,
Louis

**Comment by MystPi** [comment]
Ah, okay. Wasn't sure about this because typically the "responsible party" is the first argument to a function for ease of piping. I'll def change this. Would this count as a breaking change?

**Comment by lpil** [comment]
It would, aye.

**Comment by MystPi** [comment]
It just seems weird to me to increment the major version so close to the initial release of the package. I may just increment the minor version since I don't think anyone is using the package yet.

**Comment by lpil** [comment]
I personally have more confidence in a dependency when they demonstrate that they are versioning appropriately. I would like us to embrace appropriately high version numbers as an indicator of quality!

**Comment by MystPi** [comment]
Got it; I'll def follow semver for this one then.

For some reason it just seems harder to think of a "major" version as simply a breaking change, nothing more. Maybe that stems from some projects using semver incorrectly or not using it at all, etc.

**Comment by MystPi** [comment]
v2.0.0 addresses this issue.

https://github.com/MystPi/glen/blob/main/CHANGELOG.md#v200---2024-02-05
