### ISSUE TITLE
Expose and document API using JS request and response types

### ISSUE THREAD

**Issue by lpil** [MystPi/glen#2]
It seems the only way to use this library is with Deno or other environments that have a very similar API, but internally this library works with any JS request and response.

It would be fab if functions were exposed to convert from a JS request into a Glen request, and from a Glen response into a JS response.

I would be tempted to also remove the custom serve function in favour of this, as it's quite convoluted to use unless the server you're using has exactly the same API as deno.

Thanks,
Louis

**Comment by MystPi** [comment]
Will do! Didn't think about this initially when making the lib.

**Comment by MystPi** [comment]
Completed in 18f2fba.
